name: name_to_change
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  dio: ^5.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
